/* ============================================================
   BODEGAVAULT — Datos del Juego
   ============================================================ */

const RARITIES = {
  common:    { id:'common',    name:'Común',      color:'#9e9e9e', bg:'rgba(158,158,158,0.15)', xpMult:1   },
  rare:      { id:'rare',      name:'Raro',        color:'#2196f3', bg:'rgba(33,150,243,0.15)',  xpMult:2   },
  epic:      { id:'epic',      name:'Épico',       color:'#9c27b0', bg:'rgba(156,39,176,0.15)',  xpMult:4   },
  legendary: { id:'legendary', name:'Legendario',  color:'#ff9800', bg:'rgba(255,152,0,0.15)',   xpMult:8   },
  unique:    { id:'unique',    name:'Único',       color:'#e91e63', bg:'rgba(233,30,99,0.15)',   xpMult:20  },
  exotic:    { id:'exotic',    name:'Exótico',     color:'#39FF14', bg:'rgba(57,255,20,0.12)',   xpMult:50  },
};

const CONDITIONS = {
  new:          { id:'new',          name:'Nuevo',      valueMult:1.5,  color:'#4caf50', repairCost:0   },
  used:         { id:'used',         name:'Usado',      valueMult:1.0,  color:'#8bc34a', repairCost:30  },
  damaged:      { id:'damaged',      name:'Dañado',     valueMult:0.6,  color:'#ff9800', repairCost:80  },
  very_damaged: { id:'very_damaged', name:'Muy Dañado', valueMult:0.3,  color:'#f44336', repairCost:150 },
};

const CONDITION_ORDER = ['new','used','damaged','very_damaged'];

const CATEGORIES = {
  videogames:    { id:'videogames',    name:'Videojuegos',   icon:'🎮', color:'#e91e63' },
  electronics:   { id:'electronics',   name:'Electrónica',   icon:'💻', color:'#2196f3' },
  machines:      { id:'machines',      name:'Máquinas',      icon:'⚙️', color:'#607d8b' },
  rarities:      { id:'rarities',      name:'Rarezas',       icon:'💎', color:'#9c27b0' },
  art:           { id:'art',           name:'Arte',          icon:'🎨', color:'#ff5722' },
  music:         { id:'music',         name:'Música',        icon:'🎵', color:'#4caf50' },
  toys:          { id:'toys',          name:'Juguetes',      icon:'🧸', color:'#ff9800' },
  sports:        { id:'sports',        name:'Deportes',      icon:'⚽', color:'#00bcd4' },
  entertainment: { id:'entertainment', name:'Entretenimiento',icon:'🎬', color:'#673ab7' },
  mystery:       { id:'mystery',       name:'Objetos Raros', icon:'❓', color:'#795548' },
  everyday:      { id:'everyday',      name:'Cotidianos',    icon:'🏠', color:'#78909c' },
  valuables:     { id:'valuables',     name:'Valiosos',      icon:'💰', color:'#ffc107' },
};

// ── AVATARES ──────────────────────────────────────────────
const AVATARS = [
  '🧑','👦','👧','👨','👩','🧔','👴','👵','🧙','🧝',
  '🧛','🤴','👸','🦸','🕵️','👮','🧑‍💻','🧑‍🎨','🧑‍🔬','🧑‍🚀',
  '🧑‍🏭','🤠','🥷','🎭','🧑‍🎤','🦊','🐺','🦁','🐉','⚡',
];

const CATALOG = [
  // ── EXCLUSIVOS (solo por recompensas de nivel) ────────────
  { id:'exclusive_compass', name:'Brújula Náutica de Capitán', category:'rarities', rarity:'rare',      baseValue:600,   emoji:'🧭', desc:'Exclusiva de nivel 6. Solo existe una por jugador.', exclusive:true },
  { id:'exclusive_lamp',    name:'Lámpara de Araña Imperial',  category:'art',      rarity:'epic',      baseValue:1400,  emoji:'🏮', desc:'Exclusiva de nivel 9. Pieza única de colección.',    exclusive:true },
  { id:'exclusive_armor',   name:'Armadura Medieval',          category:'rarities', rarity:'legendary', baseValue:4500,  emoji:'🛡️', desc:'Exclusiva de nivel 15. Forjada a mano.',             exclusive:true },
  { id:'exclusive_crown',   name:'Corona Imperial',            category:'rarities', rarity:'unique',    baseValue:25000, emoji:'👑', desc:'Exclusiva de nivel 20. Solo los grandes coleccionistas la poseen.', exclusive:true },
  // ── VIDEOJUEGOS ──────────────────────────────────────────
  { id:'nes',          name:'Nintendo NES',           category:'videogames',  rarity:'rare',      baseValue:350,  emoji:'🎮', desc:'Consola 8-bit que definió una generación.' },
  { id:'gameboy',      name:'Game Boy Original',      category:'videogames',  rarity:'rare',      baseValue:280,  emoji:'🕹️', desc:'La icónica portátil gris de Nintendo, 1989.' },
  { id:'atari_2600',   name:'Atari 2600',             category:'videogames',  rarity:'rare',      baseValue:320,  emoji:'🕹️', desc:'La primera consola doméstica masiva.' },
  { id:'snes',         name:'Super Nintendo SNES',    category:'videogames',  rarity:'epic',      baseValue:500,  emoji:'🎮', desc:'Maestría gráfica de 16 bits.' },
  { id:'n64',          name:'Nintendo 64',            category:'videogames',  rarity:'rare',      baseValue:400,  emoji:'🎮', desc:'La revolución del 3D doméstico.' },
  { id:'ps1',          name:'PlayStation 1',          category:'videogames',  rarity:'common',    baseValue:200,  emoji:'🎮', desc:'El inicio de la era PlayStation.' },
  { id:'gbc',          name:'Game Boy Color',         category:'videogames',  rarity:'common',    baseValue:150,  emoji:'🕹️', desc:'La portátil que trajo color a Nintendo.' },
  { id:'game_watch',   name:'Game & Watch',           category:'videogames',  rarity:'legendary', baseValue:1200, emoji:'⌚', desc:'El precursor de todas las portátiles Nintendo.' },
  { id:'vectrex',      name:'Vectrex',                category:'videogames',  rarity:'epic',      baseValue:800,  emoji:'📺', desc:'Consola con pantalla vectorial integrada, 1982.' },
  { id:'sega_genesis', name:'SEGA Genesis',           category:'videogames',  rarity:'rare',      baseValue:350,  emoji:'🎮', desc:'"SEGA does what Nintendon\'t."' },
  { id:'virtualboy',   name:'Virtual Boy',            category:'videogames',  rarity:'epic',      baseValue:700,  emoji:'🥽', desc:'El experimento en realidad virtual de Nintendo.' },
  { id:'neo_geo',      name:'Neo Geo AES',            category:'videogames',  rarity:'legendary', baseValue:1800, emoji:'🕹️', desc:'La consola arcade más poderosa de su era.' },
  { id:'gba',          name:'Game Boy Advance SP',    category:'videogames',  rarity:'common',    baseValue:180,  emoji:'🕹️', desc:'La portátil plegable de Nintendo, 2003.' },
  { id:'sega_cd',      name:'SEGA CD',                category:'videogames',  rarity:'epic',      baseValue:650,  emoji:'📀', desc:'El addon de CD para Genesis que casi nadie recuerda.' },
  // ── ELECTRÓNICA ──────────────────────────────────────────
  { id:'mac_classic',  name:'Macintosh Classic',      category:'electronics', rarity:'epic',      baseValue:600,  emoji:'🖥️', desc:'El primer Macintosh asequible de Apple, 1984.' },
  { id:'ibm_5150',     name:'IBM PC 5150',            category:'electronics', rarity:'legendary', baseValue:2000, emoji:'🖥️', desc:'El ordenador que definió el estándar PC.' },
  { id:'c64',          name:'Commodore 64',           category:'electronics', rarity:'rare',      baseValue:450,  emoji:'⌨️', desc:'El ordenador doméstico más vendido de la historia.' },
  { id:'walkman',      name:'Sony Walkman TPS-L2',    category:'electronics', rarity:'epic',      baseValue:750,  emoji:'🎧', desc:'El primer Walkman jamás producido, 1979.' },
  { id:'hp12c',        name:'Calculadora HP-12C',     category:'electronics', rarity:'common',    baseValue:180,  emoji:'🔢', desc:'Calculadora financiera legendaria.' },
  { id:'polaroid',     name:'Polaroid SX-70',         category:'electronics', rarity:'rare',      baseValue:380,  emoji:'📷', desc:'La primera cámara Polaroid plegable SLR.' },
  { id:'betamax',      name:'Sony Betamax',           category:'electronics', rarity:'rare',      baseValue:290,  emoji:'📹', desc:'El formato que perdió la guerra VHS vs Beta.' },
  { id:'rotary_phone', name:'Teléfono Rotatorio',     category:'electronics', rarity:'common',    baseValue:120,  emoji:'☎️', desc:'Teléfono de disco de baquelita negra, años 60.' },
  { id:'radio_trans',  name:'Radio Transistor',       category:'electronics', rarity:'common',    baseValue:90,   emoji:'📻', desc:'Pequeña radio portátil de los años 60.' },
  { id:'apple1_rep',   name:'Apple I (Réplica)',      category:'electronics', rarity:'unique',    baseValue:15000,emoji:'💻', desc:'Una rarísima réplica del primer ordenador de Apple.' },
  { id:'amiga500',     name:'Commodore Amiga 500',    category:'electronics', rarity:'epic',      baseValue:550,  emoji:'🖥️', desc:'La joya de los ordenadores personales de 16 bits.' },
  // ── MÁQUINAS ─────────────────────────────────────────────
  { id:'underwood',    name:'Máquina de Escribir Underwood', category:'machines', rarity:'common', baseValue:160, emoji:'⌨️', desc:'Máquina de escribir mecánica clásica americana.' },
  { id:'leica_m3',     name:'Cámara Leica M3',        category:'machines',    rarity:'epic',      baseValue:900,  emoji:'📷', desc:'Una de las mejores cámaras telemetría jamás fabricadas.' },
  { id:'proj_8mm',     name:'Proyector 8mm',          category:'machines',    rarity:'rare',      baseValue:250,  emoji:'🎞️', desc:'Proyector de cine doméstico de los años 60.' },
  { id:'coffee_grd',   name:'Molinillo de Café Antiguo', category:'machines', rarity:'common',    baseValue:80,   emoji:'☕', desc:'Molinillo de café de madera y hierro fundido.' },
  { id:'pocket_watch', name:'Reloj de Bolsillo Dorado', category:'machines',  rarity:'rare',      baseValue:420,  emoji:'⌚', desc:'Reloj de bolsillo con cadena dorada, circa 1920.' },
  { id:'singer',       name:'Máquina de Coser Singer', category:'machines',   rarity:'common',    baseValue:200,  emoji:'🪡', desc:'La icónica máquina de coser negra de pedal.' },
  { id:'pharmacy_sc',  name:'Balanza de Farmacia',    category:'machines',    rarity:'rare',      baseValue:300,  emoji:'⚖️', desc:'Balanza de precisión de latón y cristal.' },
  { id:'enigma_rep',   name:'Máquina Enigma (Réplica)', category:'machines',  rarity:'legendary', baseValue:2500, emoji:'🔐', desc:'Réplica funcional de la famosa máquina de cifrado.' },
  { id:'dietz_lantern',name:'Linterna Dietz',         category:'machines',    rarity:'common',    baseValue:70,   emoji:'🪔', desc:'Linterna de queroseno clásica americana.' },
  // ── RAREZAS ──────────────────────────────────────────────
  { id:'coin_1870',    name:'Moneda 5 Pesetas 1870',  category:'rarities',    rarity:'epic',      baseValue:850,  emoji:'🪙', desc:'Moneda española de plata del período isabelino.' },
  { id:'silver_dol',   name:'Dólar de Plata 1957',    category:'rarities',    rarity:'rare',      baseValue:380,  emoji:'💵', desc:'Certificado de plata de los Estados Unidos.' },
  { id:'wagner_card',  name:'Carta T206 H. Wagner',   category:'rarities',    rarity:'unique',    baseValue:50000,emoji:'⚾', desc:'Una de las cartas de béisbol más raras del mundo.' },
  { id:'penny_black',  name:'Sello Penny Black 1840', category:'rarities',    rarity:'legendary', baseValue:3500, emoji:'📮', desc:'El primer sello postal del mundo.' },
  { id:'chess_ivory',  name:'Ajedrez de Marfil',      category:'rarities',    rarity:'epic',      baseValue:1200, emoji:'♟️', desc:'Juego de ajedrez tallado en marfil, S.XIX.' },
  { id:'globe_antq',   name:'Globo Terráqueo Antiguo',category:'rarities',    rarity:'rare',      baseValue:550,  emoji:'🌍', desc:'Globo de madera y papel maché, circa 1890.' },
  { id:'nautical_map', name:'Mapa Náutico Antiguo',   category:'rarities',    rarity:'rare',      baseValue:490,  emoji:'🗺️', desc:'Mapa náutico del Caribe, siglo XVIII.' },
  { id:'compass',      name:'Brújula de Marina',      category:'rarities',    rarity:'rare',      baseValue:320,  emoji:'🧭', desc:'Brújula de latón para navegación oceánica.' },
  { id:'ammonite',     name:'Fósil de Amonita',       category:'rarities',    rarity:'common',    baseValue:140,  emoji:'🐚', desc:'Fósil de cefalópodo de 150 millones de años.' },
  // ── ARTE ─────────────────────────────────────────────────
  { id:'art_nouveau',  name:'Litografía Art Nouveau', category:'art',         rarity:'rare',      baseValue:480,  emoji:'🖼️', desc:'Obra litográfica de estilo art nouveau, circa 1900.' },
  { id:'bronze_fig',   name:'Figura de Bronce',       category:'art',         rarity:'epic',      baseValue:950,  emoji:'🗿', desc:'Figura de bronce fundido, estilo modernista.' },
  { id:'chinese_vase', name:'Jarrón de Porcelana China', category:'art',      rarity:'epic',      baseValue:1100, emoji:'🏺', desc:'Jarrón de la dinastía Ming, posible réplica tardía.' },
  { id:'venetian_mir', name:'Espejo Veneciano',        category:'art',        rarity:'rare',      baseValue:620,  emoji:'🪞', desc:'Espejo decorado con técnica veneciana, S.XIX.' },
  { id:'grandfather_c',name:'Reloj de Pie Victoriano', category:'art',        rarity:'legendary', baseValue:2200, emoji:'🕰️', desc:'Majestuoso reloj de caja alta, periodo victoriano.' },
  { id:'oil_painting', name:'Óleo Flamenco S.XVII',   category:'art',         rarity:'legendary', baseValue:3000, emoji:'🖼️', desc:'Pintura al óleo de escuela flamenca, autoría incierta.' },
  // ── MÚSICA ───────────────────────────────────────────────
  { id:'les_paul_rep', name:'Gibson Les Paul 1959',   category:'music',       rarity:'legendary', baseValue:1800, emoji:'🎸', desc:'Réplica vintage de la guitarra más legendaria.' },
  { id:'harmonica',    name:'Hohner Cromática',       category:'music',       rarity:'common',    baseValue:110,  emoji:'🎵', desc:'Harmónica cromática de metal de los años 50.' },
  { id:'beatles_vinyl',name:'Vinilo Original Beatles',category:'music',       rarity:'epic',      baseValue:800,  emoji:'💿', desc:'Disco de vinilo original "Abbey Road", 1969.' },
  { id:'music_box',    name:'Caja de Música Suiza',   category:'music',       rarity:'rare',      baseValue:440,  emoji:'🎶', desc:'Caja de música mecánica de cilindro, circa 1880.' },
  { id:'banjo_1920',   name:'Banjo de los Años 20',   category:'music',       rarity:'rare',      baseValue:520,  emoji:'🪕', desc:'Banjo de 5 cuerdas de la era del jazz.' },
  { id:'theremin',     name:'Theremin RCA',              category:'music',    rarity:'legendary', baseValue:2800,   emoji:'📡', desc:'Instrumento electrónico sin contacto, rarísimo.' },
  // ── TECNOLOGÍA RETRO ─────────────────────────────────────
  { id:'consola_retro',        name:'Consola Retro',               category:'videogames',  rarity:'common',    baseValue:150,   emoji:'🎮', desc:'Consola de los 80s, plástico gris desgastado y botones simples.' },
  { id:'cartucho_antiguo',     name:'Cartucho Antiguo',            category:'videogames',  rarity:'common',    baseValue:80,    emoji:'🕹️', desc:'Cartucho clásico con etiqueta gastada. ¿Qué juego habrá dentro?' },
  { id:'disco_videojuego',     name:'Disco de Videojuego Raro',    category:'videogames',  rarity:'rare',      baseValue:600,   emoji:'💿', desc:'CD brillante con diseño futurista en caja abierta.' },
  { id:'control_vintage',      name:'Control Vintage',             category:'videogames',  rarity:'common',    baseValue:120,   emoji:'🕹️', desc:'Control noventero con cable y botones grandes.' },
  { id:'arcade_portatil',      name:'Arcade Portátil',             category:'videogames',  rarity:'rare',      baseValue:800,   emoji:'👾', desc:'Pequeña máquina arcade de mano con pantalla iluminada.' },
  { id:'arcade_mini',          name:'Máquina Arcade Mini',         category:'videogames',  rarity:'rare',      baseValue:1200,  emoji:'🕹️', desc:'Arcade en miniatura con luces neón y pantalla encendida.' },
  { id:'gameboy_clasica',      name:'GameBoy Clásica',             category:'videogames',  rarity:'rare',      baseValue:1500,  emoji:'🎮', desc:'La portátil gris con pantalla verde. Icono de una generación.' },
  { id:'consola_ed_limitada',  name:'Consola Edición Limitada',    category:'videogames',  rarity:'unique',    baseValue:45000, emoji:'🌟', desc:'Consola con diseño exclusivo y colores especiales. Solo existieron 500 unidades.' },
  { id:'usb_antigua',          name:'Memoria USB Antigua',         category:'electronics', rarity:'common',    baseValue:60,    emoji:'💾', desc:'USB vieja, diseño simple, algo rayada.' },
  { id:'computadora_vieja',    name:'Computadora Vieja',           category:'electronics', rarity:'common',    baseValue:200,   emoji:'🖥️', desc:'PC de escritorio antiguo, monitor grande beige.' },
  { id:'monitor_crt',          name:'Monitor CRT',                 category:'electronics', rarity:'common',    baseValue:250,   emoji:'📺', desc:'Pantalla gruesa encendida con estática. Pesa una tonelada.' },
  { id:'teclado_vintage',      name:'Teclado Mecánico Vintage',    category:'electronics', rarity:'rare',      baseValue:700,   emoji:'⌨️', desc:'Teclas grandes y gastadas que hacen un clack satisfactorio.' },
  { id:'mouse_antiguo',        name:'Mouse Antiguo',               category:'electronics', rarity:'common',    baseValue:70,    emoji:'🖱️', desc:'Mouse de bola color gris con cable visible.' },
  { id:'camara_digital_vieja', name:'Cámara Digital Vieja',        category:'electronics', rarity:'common',    baseValue:180,   emoji:'📷', desc:'Cámara compacta de los 2000 con lente pequeño.' },
  { id:'walkman_clasico',      name:'Walkman Clásico',             category:'electronics', rarity:'rare',      baseValue:500,   emoji:'🎧', desc:'Reproductor de cassette portátil con audífonos.' },
  { id:'discman',              name:'Discman',                     category:'electronics', rarity:'common',    baseValue:300,   emoji:'💿', desc:'Reproductor de CD portátil con tapa abierta.' },
  { id:'telefono_disco',       name:'Teléfono de Disco',           category:'electronics', rarity:'rare',      baseValue:800,   emoji:'☎️', desc:'Teléfono antiguo con rueda numérica.' },
  { id:'nokia_clasico',        name:'Teléfono Nokia Clásico',      category:'electronics', rarity:'common',    baseValue:150,   emoji:'📱', desc:'Celular antiguo pequeño con pantalla verde. Indestructible.' },
  { id:'smartphone_antiguo',   name:'Smartphone Antiguo',          category:'electronics', rarity:'common',    baseValue:100,   emoji:'📱', desc:'Smartphone viejo con bordes gruesos y pantalla rayada.' },
  { id:'radio_vieja',          name:'Radio Vieja',                 category:'electronics', rarity:'common',    baseValue:180,   emoji:'📻', desc:'Radio portátil antigua con antena extendida.' },
  // ── JUGUETES Y FIGURAS ───────────────────────────────────
  { id:'figura_accion',        name:'Figura de Acción',            category:'toys',        rarity:'common',    baseValue:100,   emoji:'🦸', desc:'Figura articulada de superhéroe con colores llamativos.' },
  { id:'minifigura_colec',     name:'Minifigura Coleccionable',    category:'toys',        rarity:'common',    baseValue:80,    emoji:'🧩', desc:'Figura pequeña estilo bloque, cara simple.' },
  { id:'muneca_antigua',       name:'Muñeca Antigua',              category:'toys',        rarity:'rare',      baseValue:600,   emoji:'👗', desc:'Muñeca de porcelana con vestido clásico. Ojos de cristal.' },
  { id:'peluche_vintage',      name:'Peluche Vintage',             category:'toys',        rarity:'common',    baseValue:90,    emoji:'🧸', desc:'Oso de peluche viejo con costuras visibles.' },
  { id:'carrito_metal',        name:'Carrito de Metal',            category:'toys',        rarity:'common',    baseValue:120,   emoji:'🚗', desc:'Coche de juguete metálico con pintura desgastada.' },
  { id:'avion_juguete',        name:'Avión de Juguete',            category:'toys',        rarity:'common',    baseValue:80,    emoji:'✈️', desc:'Avión pequeño de plástico con colores brillantes.' },
  { id:'tren_electrico',       name:'Tren Eléctrico',              category:'toys',        rarity:'rare',      baseValue:1000,  emoji:'🚂', desc:'Tren de juguete con rieles. Funciona con pila.' },
  { id:'robot_juguete',        name:'Robot de Juguete',            category:'toys',        rarity:'rare',      baseValue:900,   emoji:'🤖', desc:'Robot retro con diseño cuadrado y ojos luminosos.' },
  { id:'dinosaurio_plastico',  name:'Dinosaurio de Plástico',      category:'toys',        rarity:'common',    baseValue:70,    emoji:'🦕', desc:'Figura de dinosaurio verde texturizado.' },
  { id:'figura_ed_limitada',   name:'Figura Edición Limitada',     category:'toys',        rarity:'epic',      baseValue:3500,  emoji:'📦', desc:'Figura en caja sellada con número de edición.' },
  { id:'figura_firmada_col',   name:'Figura Firmada',              category:'toys',        rarity:'unique',    baseValue:38000, emoji:'✍️', desc:'Figura con firma original del creador en la caja. Irrepetible.' },
  { id:'set_juguetes_antiguo', name:'Set de Juguetes Antiguo',     category:'toys',        rarity:'rare',      baseValue:1200,  emoji:'🎁', desc:'Colección de juguetes en caja original.' },
  { id:'trompo',               name:'Trompo',                      category:'toys',        rarity:'common',    baseValue:60,    emoji:'🪀', desc:'Trompo de madera colorido.' },
  { id:'yoyo',                 name:'Yoyo',                        category:'toys',        rarity:'common',    baseValue:70,    emoji:'🪀', desc:'Yoyo clásico con cuerda.' },
  { id:'canicas_antiguas',     name:'Canicas Antiguas',            category:'toys',        rarity:'common',    baseValue:80,    emoji:'⚪', desc:'Varias canicas brillantes de cristal.' },
  { id:'muneco_cuerda',        name:'Muñeco de Cuerda',            category:'toys',        rarity:'rare',      baseValue:500,   emoji:'🤖', desc:'Juguete mecánico con llave de cuerda.' },
  { id:'castillo_juguete',     name:'Castillo de Juguete',         category:'toys',        rarity:'rare',      baseValue:900,   emoji:'🏰', desc:'Castillo miniatura medieval con torre y foso.' },
  { id:'pistola_juguete_vin',  name:'Pistola de Juguete Vintage',  category:'toys',        rarity:'common',    baseValue:150,   emoji:'🔫', desc:'Pistola antigua de plástico con tapa de corcho.' },
  { id:'juego_mesa_antiguo',   name:'Juego de Mesa Antiguo',       category:'toys',        rarity:'rare',      baseValue:700,   emoji:'🎲', desc:'Caja vieja de juego de mesa con manual en papel amarillo.' },
  { id:'rompecabezas_viejo',   name:'Rompecabezas Viejo',          category:'toys',        rarity:'common',    baseValue:100,   emoji:'🧩', desc:'Puzzle incompleto sobre mesa. Faltan tres piezas.' },
  // ── DEPORTES ─────────────────────────────────────────────
  { id:'jersey_firmado',       name:'Jersey Firmado',              category:'sports',      rarity:'unique',    baseValue:50000, emoji:'👕', desc:'Camiseta deportiva con firma auténtica de leyenda. Certificado de autenticidad incluido.' },
  { id:'balon_firmado',        name:'Balón Firmado',               category:'sports',      rarity:'epic',      baseValue:4000,  emoji:'⚽', desc:'Balón con autógrafo de jugador famoso.' },
  { id:'tarjeta_deportiva',    name:'Tarjeta Deportiva',           category:'sports',      rarity:'rare',      baseValue:1500,  emoji:'🃏', desc:'Tarjeta coleccionable brillante de jugador estrella.' },
  { id:'bate_firmado',         name:'Bate Firmado',                category:'sports',      rarity:'epic',      baseValue:3500,  emoji:'⚾', desc:'Bate de madera con firma visible y fecha.' },
  { id:'guante_antiguo',       name:'Guante Antiguo',              category:'sports',      rarity:'common',    baseValue:200,   emoji:'🥊', desc:'Guante de béisbol desgastado con forma del usuario.' },
  { id:'trofeo_viejo',         name:'Trofeo Viejo',                category:'sports',      rarity:'rare',      baseValue:800,   emoji:'🏆', desc:'Trofeo dorado con una capa de polvo histórico.' },
  { id:'medalla_deportiva',    name:'Medalla Deportiva',           category:'sports',      rarity:'rare',      baseValue:600,   emoji:'🥇', desc:'Medalla colgante con cinta desgastada.' },
  { id:'casco_deportivo',      name:'Casco Deportivo',             category:'sports',      rarity:'rare',      baseValue:1000,  emoji:'⛑️', desc:'Casco usado con marcas de impacto.' },
  { id:'zapatos_vintage',      name:'Zapatos Vintage',             category:'sports',      rarity:'rare',      baseValue:1200,  emoji:'👟', desc:'Tenis deportivos de edición clásica, colores desgastados.' },
  { id:'poster_firmado',       name:'Póster Firmado',              category:'sports',      rarity:'rare',      baseValue:1800,  emoji:'📋', desc:'Póster con firma de atleta famoso.' },
  { id:'foto_firmada',         name:'Foto Firmada',                category:'sports',      rarity:'rare',      baseValue:1500,  emoji:'📸', desc:'Fotografía deportiva autografiada en el momento decisivo.' },
  { id:'banderin',             name:'Banderín',                    category:'sports',      rarity:'common',    baseValue:100,   emoji:'🚩', desc:'Banderín triangular de equipo.' },
  { id:'ticket_antiguo',       name:'Ticket Antiguo',              category:'sports',      rarity:'common',    baseValue:200,   emoji:'🎫', desc:'Boleto viejo de evento deportivo histórico.' },
  { id:'revista_deportiva',    name:'Revista Deportiva',           category:'sports',      rarity:'common',    baseValue:150,   emoji:'📰', desc:'Revista vieja abierta en la página del campeón.' },
  { id:'carta_rara_sport',     name:'Carta Rara de Jugador',       category:'sports',      rarity:'unique',    baseValue:55000, emoji:'⭐', desc:'Carta de jugador con impresión defectuosa de fábrica. Solo existen 50.' },
  { id:'camiseta_vintage',     name:'Camiseta Vintage',            category:'sports',      rarity:'common',    baseValue:300,   emoji:'👕', desc:'Camiseta deportiva vieja de temporada clásica.' },
  { id:'bufanda_equipo',       name:'Bufanda de Equipo',           category:'sports',      rarity:'common',    baseValue:120,   emoji:'🧣', desc:'Bufanda con colores del equipo campeón.' },
  { id:'figura_deportiva',     name:'Figura Deportiva',            category:'sports',      rarity:'rare',      baseValue:700,   emoji:'🏃', desc:'Figura de jugador en posición de juego.' },
  { id:'disco_conmemorativo',  name:'Disco Conmemorativo',         category:'sports',      rarity:'rare',      baseValue:900,   emoji:'🥉', desc:'Placa deportiva metálica de campeonato.' },
  { id:'album_estampas',       name:'Álbum de Estampas',           category:'sports',      rarity:'rare',      baseValue:600,   emoji:'📖', desc:'Álbum de estampas parcialmente lleno.' },
  // ── MÚSICA (nuevos) ──────────────────────────────────────
  { id:'vinilo_clasico',       name:'Vinilo Clásico',              category:'music',       rarity:'common',    baseValue:200,   emoji:'🎵', desc:'Disco negro con portada vintage.' },
  { id:'cassette_cinta',       name:'Cassette',                    category:'music',       rarity:'common',    baseValue:100,   emoji:'📼', desc:'Cinta transparente antigua. Las caras A y B.' },
  { id:'cd_raro',              name:'CD Raro',                     category:'music',       rarity:'rare',      baseValue:500,   emoji:'💿', desc:'CD brillante con diseño edición especial.' },
  { id:'poster_banda',         name:'Póster de Banda',             category:'music',       rarity:'common',    baseValue:150,   emoji:'🎸', desc:'Póster musical de banda icónica.' },
  { id:'autografo_musical',    name:'Autógrafo Musical',           category:'music',       rarity:'rare',      baseValue:800,   emoji:'✍️', desc:'Firma en papel de artista reconocido.' },
  { id:'guitarra_vieja',       name:'Guitarra Vieja',              category:'music',       rarity:'unique',    baseValue:42000, emoji:'🎸', desc:'Guitarra acústica con historia. Perteneció a alguien famoso.' },
  { id:'microfono_vintage',    name:'Micrófono Vintage',           category:'music',       rarity:'rare',      baseValue:1500,  emoji:'🎤', desc:'Micrófono antiguo metálico estilo cabaret.' },
  { id:'bocina_antigua',       name:'Bocina Antigua',              category:'music',       rarity:'rare',      baseValue:1200,  emoji:'🔊', desc:'Altavoz grande viejo con bocina de madera.' },
  { id:'radio_portatil',       name:'Radio Portátil',              category:'music',       rarity:'common',    baseValue:180,   emoji:'📻', desc:'Radio pequeña retro con antena.' },
  { id:'tocadiscos',           name:'Tocadiscos',                  category:'music',       rarity:'rare',      baseValue:1800,  emoji:'🎶', desc:'Reproductor de vinilo abierto. Aún gira.' },
  { id:'partitura',            name:'Partitura',                   category:'music',       rarity:'common',    baseValue:120,   emoji:'🎼', desc:'Hojas con notas musicales manuscritas.' },
  { id:'revista_musical',      name:'Revista Musical',             category:'music',       rarity:'common',    baseValue:100,   emoji:'📰', desc:'Revista antigua de música con entrevista histórica.' },
  { id:'entrada_concierto',    name:'Entrada de Concierto',        category:'music',       rarity:'common',    baseValue:200,   emoji:'🎫', desc:'Ticket de concierto de leyenda.' },
  { id:'disco_firmado',        name:'Disco Firmado',               category:'music',       rarity:'legendary', baseValue:12000, emoji:'💿', desc:'Vinilo autografiado por el artista en la portada.' },
  { id:'instrumento_mini',     name:'Instrumento Mini',            category:'music',       rarity:'rare',      baseValue:600,   emoji:'🎻', desc:'Instrumento pequeño de colección.' },
  { id:'caja_musical_gen',     name:'Caja Musical',                category:'music',       rarity:'rare',      baseValue:900,   emoji:'🎵', desc:'Caja musical vintage con mecanismo de cilindro.' },
  { id:'audifonos_viejos',     name:'Audífonos Viejos',            category:'music',       rarity:'common',    baseValue:150,   emoji:'🎧', desc:'Auriculares grandes acolchados de los 70s.' },
  { id:'mezcladora_vieja',     name:'Mezcladora',                  category:'music',       rarity:'rare',      baseValue:2000,  emoji:'🎛️', desc:'Consola de audio analógica con muchos botones.' },
  { id:'grabadora',            name:'Grabadora',                   category:'music',       rarity:'common',    baseValue:250,   emoji:'🎙️', desc:'Grabadora portátil de cassette.' },
  { id:'amplificador_viejo',   name:'Amplificador',                category:'music',       rarity:'rare',      baseValue:1500,  emoji:'🔊', desc:'Amplificador vintage de tubos. Sonido cálido.' },
  // ── ANTIGÜEDADES (nuevos) ────────────────────────────────
  { id:'reloj_antiguo_gen',    name:'Reloj Antiguo',               category:'machines',    rarity:'rare',      baseValue:1800,  emoji:'⏱️', desc:'Reloj dorado clásico de mesa.' },
  { id:'reloj_bolsillo',       name:'Reloj de Bolsillo',           category:'machines',    rarity:'rare',      baseValue:2000,  emoji:'⌚', desc:'Reloj abierto con cadena. Las manecillas aún se mueven.' },
  { id:'maquina_escribir_gen', name:'Máquina de Escribir Vintage', category:'machines',    rarity:'rare',      baseValue:1200,  emoji:'⌨️', desc:'Máquina mecánica con todas las teclas.' },
  { id:'telescopio_viejo',     name:'Telescopio Viejo',            category:'machines',    rarity:'unique',    baseValue:48000, emoji:'🔭', desc:'Telescopio de latón del siglo XIX. Con él se descubrió algo importante.' },
  { id:'camara_analogica',     name:'Cámara Analógica',            category:'machines',    rarity:'rare',      baseValue:1500,  emoji:'📷', desc:'Cámara antigua con rollo adentro sin revelar.' },
  { id:'lampara_vintage',      name:'Lámpara Vintage',             category:'machines',    rarity:'common',    baseValue:300,   emoji:'🪔', desc:'Lámpara de pie con pantalla de tela y luz cálida.' },
  { id:'cuadro_antiguo',       name:'Cuadro Antiguo',              category:'art',         rarity:'rare',      baseValue:2000,  emoji:'🖼️', desc:'Pintura clásica en marco dorado.' },
  { id:'estatua_pequena',      name:'Estatua Pequeña',             category:'art',         rarity:'rare',      baseValue:1800,  emoji:'🗿', desc:'Escultura pequeña de mármol o bronce.' },
  { id:'cofre_viejo',          name:'Cofre Viejo',                 category:'rarities',    rarity:'rare',      baseValue:1500,  emoji:'📦', desc:'Cofre de madera con cerradura oxidada.' },
  { id:'libro_antiguo',        name:'Libro Antiguo',               category:'rarities',    rarity:'rare',      baseValue:1200,  emoji:'📚', desc:'Libro con páginas amarillas y olor a historia.' },
  { id:'mapa_antiguo',         name:'Mapa Antiguo',                category:'rarities',    rarity:'unique',    baseValue:52000, emoji:'🗺️', desc:'Mapa enrollado de región inexplorada. Anotaciones a pluma.' },
  { id:'moneda_rara',          name:'Moneda Rara',                 category:'rarities',    rarity:'rare',      baseValue:1000,  emoji:'🪙', desc:'Moneda metálica brillante de época desconocida.' },
  { id:'billete_antiguo',      name:'Billete Antiguo',             category:'rarities',    rarity:'common',    baseValue:350,   emoji:'💵', desc:'Billete desgastado fuera de circulación.' },
  { id:'sello_postal',         name:'Sello Postal',                category:'rarities',    rarity:'common',    baseValue:200,   emoji:'📮', desc:'Estampilla antigua con figura de personaje.' },
  { id:'pluma_fuente',         name:'Pluma Fuente',                category:'machines',    rarity:'common',    baseValue:250,   emoji:'🖊️', desc:'Pluma elegante de émbolo con tinta seca.' },
  { id:'diario_viejo',         name:'Diario Viejo',                category:'rarities',    rarity:'common',    baseValue:180,   emoji:'📓', desc:'Cuaderno antiguo con cierre de cuero.' },
  { id:'caja_fuerte_ant',      name:'Caja Fuerte Antigua',         category:'machines',    rarity:'rare',      baseValue:1500,  emoji:'🔒', desc:'Caja metálica cerrada. Nadie sabe la combinación.' },
  { id:'llave_antigua',        name:'Llave Antigua',               category:'rarities',    rarity:'common',    baseValue:150,   emoji:'🗝️', desc:'Llave oxidada de hierro forjado.' },
  { id:'reloj_pared',          name:'Reloj de Pared',              category:'machines',    rarity:'rare',      baseValue:1800,  emoji:'🕰️', desc:'Reloj colgado de péndulo que aún marca la hora.' },
  { id:'globo_vintage',        name:'Globo Terráqueo Vintage',     category:'rarities',    rarity:'rare',      baseValue:1200,  emoji:'🌍', desc:'Globo terráqueo vintage con países que ya no existen.' },
  // ── CINE Y ENTRETENIMIENTO ───────────────────────────────
  { id:'poster_pelicula',      name:'Póster de Película',          category:'entertainment',rarity:'common',   baseValue:150,   emoji:'🎬', desc:'Cartel cinematográfico enmarcado.' },
  { id:'figura_personaje',     name:'Figura de Personaje',         category:'entertainment',rarity:'rare',     baseValue:800,   emoji:'🦸', desc:'Figura detallada de personaje icónico.' },
  { id:'dvd_raro',             name:'DVD Raro',                    category:'entertainment',rarity:'rare',     baseValue:600,   emoji:'💿', desc:'Caja de DVD edición especial fuera de catálogo.' },
  { id:'vhs_cinta',            name:'VHS',                         category:'entertainment',rarity:'common',   baseValue:150,   emoji:'📼', desc:'Cinta antigua de película. Hay que rebobinarla.' },
  { id:'guion_pelicula',       name:'Guion de Película',           category:'entertainment',rarity:'rare',     baseValue:2000,  emoji:'📄', desc:'Hojas impresas con anotaciones del director.' },
  { id:'mascara_personaje',    name:'Máscara de Personaje',        category:'entertainment',rarity:'rare',     baseValue:1500,  emoji:'🎭', desc:'Máscara de personaje famoso, ligeramente desgastada.' },
  { id:'prop_pelicula',        name:'Prop de Película',            category:'entertainment',rarity:'unique',   baseValue:60000, emoji:'🎬', desc:'Objeto real usado en el rodaje. Certificado oficial del estudio.' },
  { id:'figura_especial',      name:'Figura Especial',             category:'entertainment',rarity:'epic',     baseValue:5000,  emoji:'🌟', desc:'Figura en vitrina de edición muy limitada.' },
  { id:'coleccion_dvd',        name:'Colección de DVD',            category:'entertainment',rarity:'rare',     baseValue:1000,  emoji:'📀', desc:'Varias cajas de saga completa.' },
  { id:'camara_filmacion',     name:'Cámara de Filmación',         category:'entertainment',rarity:'epic',     baseValue:4500,  emoji:'🎥', desc:'Cámara de filmación antigua usada en producciones reales.' },
  { id:'entrada_cine',         name:'Entrada de Cine',             category:'entertainment',rarity:'common',   baseValue:100,   emoji:'🎟️', desc:'Ticket viejo de estreno histórico.' },
  { id:'llavero_tematico',     name:'Llavero Temático',            category:'entertainment',rarity:'common',   baseValue:80,    emoji:'🗝️', desc:'Llavero de franquicia coleccionable.' },
  { id:'ropa_personaje',       name:'Ropa de Personaje',           category:'entertainment',rarity:'unique',   baseValue:65000, emoji:'👔', desc:'Traje icónico usado por el actor en pantalla. Con etiqueta de vestuario.' },
  { id:'casco_personaje',      name:'Casco de Personaje',          category:'entertainment',rarity:'epic',     baseValue:6000,  emoji:'⛑️', desc:'Casco de personaje famoso con acabados de producción.' },
  { id:'figura_firmada_cine',  name:'Figura Firmada de Cine',      category:'entertainment',rarity:'legendary',baseValue:18000, emoji:'✍️', desc:'Figura autografiada por el actor protagonista.' },
  { id:'set_coleccion',        name:'Set de Colección',            category:'entertainment',rarity:'epic',     baseValue:4000,  emoji:'🎁', desc:'Colección completa de la trilogía en caja especial.' },
  { id:'estatua_grande',       name:'Estatua Grande',              category:'entertainment',rarity:'epic',     baseValue:5500,  emoji:'🗿', desc:'Figura de gran tamaño de personaje icónico.' },
  { id:'libro_arte',           name:'Libro de Arte',               category:'entertainment',rarity:'rare',     baseValue:1200,  emoji:'📚', desc:'Libro ilustrado con arte conceptual de producción.' },
  { id:'tarjeta_promo',        name:'Tarjeta Promo',               category:'entertainment',rarity:'rare',     baseValue:900,   emoji:'🃏', desc:'Tarjeta especial de promoción de estreno.' },
  { id:'caja_edicion_prem',    name:'Caja Edición Premium',        category:'entertainment',rarity:'epic',     baseValue:3500,  emoji:'📦', desc:'Caja premium sellada con extras exclusivos.' },
  // ── OBJETOS EXTRAÑOS ─────────────────────────────────────
  { id:'objeto_misterioso',    name:'Objeto Misterioso',           category:'mystery',     rarity:'rare',      baseValue:1500,  emoji:'❓', desc:'Nadie sabe qué es exactamente.' },
  { id:'caja_sellada',         name:'Caja Sellada',                category:'mystery',     rarity:'rare',      baseValue:1200,  emoji:'📦', desc:'Caja cerrada sin abrir. Pesa más de lo esperado.' },
  { id:'artefacto_desc',       name:'Artefacto Desconocido',       category:'mystery',     rarity:'epic',      baseValue:5000,  emoji:'⚙️', desc:'Máquina extraña con mecanismos incomprensibles.' },
  { id:'maquina_incompleta',   name:'Máquina Incompleta',          category:'mystery',     rarity:'common',    baseValue:400,   emoji:'🔧', desc:'Partes sueltas que alguna vez formaron algo.' },
  { id:'dispositivo_raro',     name:'Dispositivo Raro',            category:'mystery',     rarity:'rare',      baseValue:1800,  emoji:'📡', desc:'Aparato desconocido que emite calor intermitente.' },
  { id:'objeto_experimental',  name:'Objeto Experimental',         category:'mystery',     rarity:'epic',      baseValue:6500,  emoji:'🔬', desc:'Tecnología extraña con etiqueta de laboratorio.' },
  { id:'prototipo',            name:'Prototipo',                   category:'mystery',     rarity:'unique',    baseValue:70000, emoji:'🛸', desc:'Pieza única de tecnología avanzada. Número de serie: 001.' },
  { id:'arte_extrano',         name:'Arte Extraño',                category:'mystery',     rarity:'rare',      baseValue:2000,  emoji:'🎨', desc:'Escultura rara que inquieta a quien la observa.' },
  { id:'objeto_alien',         name:'Objeto Alien',                category:'mystery',     rarity:'unique',    baseValue:75000, emoji:'👽', desc:'Diseño futurista sin componentes identificables. Origen inexplicado.' },
  { id:'reliquia_misteriosa',  name:'Reliquia',                    category:'mystery',     rarity:'rare',      baseValue:1500,  emoji:'🏺', desc:'Objeto antiguo raro de procedencia desconocida.' },
  { id:'maquina_rota',         name:'Máquina Rota',                category:'mystery',     rarity:'common',    baseValue:250,   emoji:'💀', desc:'Objeto dañado irrecuperable. Curioso igual.' },
  { id:'objeto_no_ident',      name:'Objeto No Identificado',      category:'mystery',     rarity:'rare',      baseValue:1000,  emoji:'🔍', desc:'Cubierto parcialmente. Nadie lo ha catalogado.' },
  { id:'dispositivo_oxidado',  name:'Dispositivo Oxidado',         category:'mystery',     rarity:'common',    baseValue:300,   emoji:'⚙️', desc:'Metal viejo con botones indescifrables.' },
  { id:'pieza_mecanica',       name:'Pieza Mecánica',              category:'mystery',     rarity:'common',    baseValue:180,   emoji:'⚙️', desc:'Engranajes y resortes de máquina desconocida.' },
  { id:'objeto_brillante',     name:'Objeto Brillante',            category:'mystery',     rarity:'rare',      baseValue:1200,  emoji:'✨', desc:'Emite una luz intensa sin batería visible.' },
  { id:'caja_rota',            name:'Caja Rota',                   category:'mystery',     rarity:'common',    baseValue:150,   emoji:'📦', desc:'Caja abierta con algo adentro que no se ve bien.' },
  { id:'aparato_extrano',      name:'Aparato Extraño',             category:'mystery',     rarity:'rare',      baseValue:1500,  emoji:'🔌', desc:'Máquina rara con cables de colores.' },
  { id:'herramienta_antigua',  name:'Herramienta Antigua',         category:'mystery',     rarity:'common',    baseValue:200,   emoji:'🔨', desc:'Herramienta vieja de uso desconocido.' },
  { id:'artefacto_mecanico',   name:'Artefacto Mecánico',          category:'mystery',     rarity:'unique',    baseValue:72000, emoji:'⚙️', desc:'Mecanismo complejo de precisión inimaginable. Funciona solo.' },
  { id:'objeto_unico_mist',    name:'Objeto Único',                category:'mystery',     rarity:'unique',    baseValue:80000, emoji:'🌟', desc:'Pieza especial irrepetible. Solo existe este ejemplar en el mundo.' },
  // ── OBJETOS DEL DÍA A DÍA ───────────────────────────────
  { id:'lata_vintage',         name:'Lata Vintage',                category:'everyday',    rarity:'common',    baseValue:80,    emoji:'🥫', desc:'Lata oxidada de producto descontinuado.' },
  { id:'botella_antigua',      name:'Botella Antigua',             category:'everyday',    rarity:'common',    baseValue:120,   emoji:'🍾', desc:'Botella de vidrio con etiqueta ilegible.' },
  { id:'caja_cereal',          name:'Caja de Cereal',              category:'everyday',    rarity:'common',    baseValue:60,    emoji:'📦', desc:'Caja vieja con mascota de cereal que ya no se vende.' },
  { id:'juguete_cajita_feliz', name:'Juguete Cajita Feliz',        category:'everyday',    rarity:'common',    baseValue:100,   emoji:'🎁', desc:'Juguete pequeño de hamburgesería.' },
  { id:'reloj_digital_ant',    name:'Reloj Digital',               category:'everyday',    rarity:'common',    baseValue:150,   emoji:'⏰', desc:'Reloj retro con display de segmentos rojos.' },
  { id:'calculadora_vieja',    name:'Calculadora',                 category:'everyday',    rarity:'common',    baseValue:120,   emoji:'🔢', desc:'Calculadora vieja con teclas duras.' },
  { id:'telefono_publico',     name:'Teléfono Público',            category:'everyday',    rarity:'rare',      baseValue:800,   emoji:'☎️', desc:'Teléfono de calle completo con cabina parcial.' },
  { id:'agenda_vieja',         name:'Agenda',                      category:'everyday',    rarity:'common',    baseValue:80,    emoji:'📒', desc:'Libreta usada con citas de otra persona.' },
  { id:'camara_desechable',    name:'Cámara Desechable',           category:'everyday',    rarity:'common',    baseValue:100,   emoji:'📸', desc:'Cámara simple con fotos sin revelar adentro.' },
  { id:'linterna_met',         name:'Linterna Metálica',           category:'everyday',    rarity:'common',    baseValue:120,   emoji:'🔦', desc:'Linterna metálica pesada. Pilas incluidas.' },
  { id:'encendedor_vin',       name:'Encendedor Vintage',          category:'everyday',    rarity:'common',    baseValue:90,    emoji:'🔥', desc:'Encendedor viejo de metal con grabado.' },
  { id:'termo',                name:'Termo Metálico',              category:'everyday',    rarity:'common',    baseValue:150,   emoji:'🧉', desc:'Termo metálico de marca antigua.' },
  { id:'radio_despertador',    name:'Radio Despertador',           category:'everyday',    rarity:'common',    baseValue:200,   emoji:'⏰', desc:'Reloj con radio AM integrada.' },
  { id:'tv_antigua',           name:'Televisión Antigua',          category:'everyday',    rarity:'rare',      baseValue:1000,  emoji:'📺', desc:'TV pequeña antigua con antena de conejo.' },
  { id:'control_remoto_ant',   name:'Control Remoto Antiguo',      category:'everyday',    rarity:'common',    baseValue:80,    emoji:'📺', desc:'Mando viejo con muchos botones sin función.' },
  { id:'ventilador_ant',       name:'Ventilador de Mesa',          category:'everyday',    rarity:'common',    baseValue:200,   emoji:'🌀', desc:'Ventilador de metal que hace ruido al girar.' },
  { id:'cafetera_antigua',     name:'Cafetera Antigua',            category:'everyday',    rarity:'common',    baseValue:250,   emoji:'☕', desc:'Cafetera de aluminio estilo italiano.' },
  { id:'taza_decorada',        name:'Taza Decorada',               category:'everyday',    rarity:'common',    baseValue:70,    emoji:'☕', desc:'Taza con diseño vintage.' },
  { id:'plato_vintage',        name:'Plato Vintage',               category:'everyday',    rarity:'common',    baseValue:80,    emoji:'🍽️', desc:'Plato con diseño de otra época.' },
  { id:'caja_metalica',        name:'Caja Metálica',               category:'everyday',    rarity:'common',    baseValue:150,   emoji:'📦', desc:'Caja resistente de metal con cierre a presión.' },
  // ── OBJETOS VALIOSOS ─────────────────────────────────────
  { id:'reloj_lujo',           name:'Reloj de Lujo',               category:'valuables',   rarity:'unique',    baseValue:72000, emoji:'⌚', desc:'Reloj elegante de manufactura suiza limitada. Solo 100 en el mundo.' },
  { id:'collar_joya',          name:'Collar de Joya',              category:'valuables',   rarity:'epic',      baseValue:7000,  emoji:'💎', desc:'Collar brillante con piedra preciosa.' },
  { id:'anillo_detallado',     name:'Anillo Detallado',            category:'valuables',   rarity:'epic',      baseValue:5500,  emoji:'💍', desc:'Anillo con grabados y gema central.' },
  { id:'joya_vintage',         name:'Joya Vintage',                category:'valuables',   rarity:'epic',      baseValue:6000,  emoji:'💎', desc:'Accesorio antiguo con piedra de color.' },
  { id:'lingote_oro',          name:'Lingote de Oro',              category:'valuables',   rarity:'legendary', baseValue:35000, emoji:'🥇', desc:'Barra de oro puro con sello de fundición.' },
  { id:'moneda_oro',           name:'Moneda de Oro',               category:'valuables',   rarity:'legendary', baseValue:20000, emoji:'🪙', desc:'Moneda dorada de alta pureza.' },
  { id:'diamante_gema',        name:'Diamante',                    category:'valuables',   rarity:'legendary', baseValue:30000, emoji:'💎', desc:'Gema brillante tallada en corte antiguo.' },
  { id:'caja_fuerte_llena',    name:'Caja Fuerte con Contenido',   category:'valuables',   rarity:'legendary', baseValue:28000, emoji:'💰', desc:'Caja abierta con dinero adentro. Nadie sabe de dónde viene.' },
  { id:'objeto_firmado_raro',  name:'Objeto Firmado Raro',         category:'valuables',   rarity:'epic',      baseValue:7500,  emoji:'✍️', desc:'Objeto de colección con firma de personalidad histórica.' },
  { id:'edicion_limitada_val', name:'Edición Limitada',            category:'valuables',   rarity:'legendary', baseValue:22000, emoji:'🌟', desc:'Objeto exclusivo producido en tirada reducida.' },
  { id:'objeto_historico',     name:'Objeto Histórico',            category:'valuables',   rarity:'unique',    baseValue:68000, emoji:'🏛️', desc:'Reliquia de evento histórico documentado. Museo lo quiere.' },
  { id:'reliquia_famosa',      name:'Reliquia Famosa',             category:'valuables',   rarity:'unique',    baseValue:82000, emoji:'🏺', desc:'Objeto icónico conocido en el mundo del coleccionismo.' },
  { id:'trofeo_importante',    name:'Trofeo Importante',           category:'valuables',   rarity:'legendary', baseValue:18000, emoji:'🏆', desc:'Premio importante de competición internacional.' },
  { id:'objeto_museo',         name:'Objeto de Museo',             category:'valuables',   rarity:'unique',    baseValue:76000, emoji:'🏛️', desc:'Pieza exhibida en museo. Tiene ficha oficial de catalogación.' },
  { id:'pieza_unica_val',      name:'Pieza Única',                 category:'valuables',   rarity:'unique',    baseValue:85000, emoji:'✨', desc:'Objeto irrepetible. El único de su clase.' },
  { id:'objeto_legendario',    name:'Objeto Legendario',           category:'valuables',   rarity:'unique',    baseValue:78000, emoji:'🌟', desc:'Objeto mítico cuya existencia se dudaba.' },
  { id:'coleccion_completa',   name:'Colección Completa',          category:'valuables',   rarity:'legendary', baseValue:32000, emoji:'🎁', desc:'Set completo de serie codiciada.' },
  { id:'arte_original',        name:'Arte Original',               category:'valuables',   rarity:'unique',    baseValue:90000, emoji:'🖼️', desc:'Pintura única de artista reconocido. Sin firma pero documentada.' },
  { id:'documento_firmado',    name:'Documento Firmado',           category:'valuables',   rarity:'epic',      baseValue:8000,  emoji:'📜', desc:'Papel con firma de personaje histórico.' },
  // ── EXCLUSIVOS CAJA DEL ABISMO ─────────────────────────
  { id:'katana_feudal',   name:'Katana Feudal Original',    category:'rarities', rarity:'legendary', baseValue:8000,   emoji:'🗡️',  desc:'Hoja forjada en Japón feudal, S.XVII. Jamás usada en batalla.', exclusive:true, abismo:true },
  { id:'diamante_xviii',  name:'Diamante Tallado S.XVIII',  category:'rarities', rarity:'legendary', baseValue:12000,  emoji:'💎',  desc:'Diamante de corte antiguo con certificado de autenticidad.', exclusive:true, abismo:true },
  { id:'matrioska_imp',   name:'Matrioska Imperial',        category:'rarities', rarity:'legendary', baseValue:9500,   emoji:'🪆',  desc:'Juego de muñecas rusas de la época zarista, pintadas a mano.', exclusive:true, abismo:true },
  { id:'manuscrito_ilum', name:'Manuscrito Iluminado',      category:'art',      rarity:'unique',    baseValue:50000,  emoji:'📜',  desc:'Manuscrito medieval con iluminaciones en pan de oro. S.XIV.', exclusive:true, abismo:true },
  { id:'tridente_rep',    name:'Tridente de Poseidón',      category:'rarities', rarity:'unique',    baseValue:75000,  emoji:'🔱',  desc:'Réplica arqueológica griega en bronce sólido, tallada a mano.', exclusive:true, abismo:true },
  // ── EXÓTICOS ───────────────────────────────────────────
  { id:'nucleo_reactor',  name:'Núcleo de Reactor Miniatura', category:'rarities', rarity:'exotic',  baseValue:120000, emoji:'☢️',  desc:'Pieza de demostración de reactor experimental, sellada en vidrio blindado.', exclusive:true, abismo:true },
  { id:'muestra_bio',     name:'Muestra Biológica Clasificada', category:'rarities', rarity:'exotic', baseValue:150000, emoji:'🧬',  desc:'Espécimen en formol con sello gubernamental ilegible. Origen desconocido.', exclusive:true, abismo:true },
  { id:'ojo_dios',        name:'Ojo de Dios (Telescopio)',   category:'machines', rarity:'exotic',   baseValue:200000, emoji:'👁️',  desc:'Telescopio victoriano con lentes de cristal de roca tallado a mano.', exclusive:true, abismo:true },
];

const NPCS = [
  {
    id:'don_miguel', name:'Don Miguel', title:'El Coleccionista', avatar:'👴',
    desc:'Coleccionista veterano con 50 años en el hobby.',
    pref:['videogames'],
    mult:{ videogames:1.25, electronics:1.0, machines:0.9, rarities:0.85, art:0.8, music:0.85 },
    tradeFreq:3,
    phrases:{ buy:['¡Esto me trae muchos recuerdos!','Por esto pago bien.','Lo llevo, ¿cuánto quieres?'] },
  },
  {
    id:'senora_torres', name:'Sra. Torres', title:'Anticuaria', avatar:'👵',
    desc:'Experta anticuaria con tienda en el centro histórico.',
    pref:['rarities','art'],
    mult:{ videogames:0.8, electronics:0.85, machines:1.0, rarities:1.3, art:1.2, music:1.1 },
    tradeFreq:2,
    phrases:{ buy:['Esto merece un lugar en mi tienda.','Rarísimo. Te hago una oferta seria.','Llevo años buscando algo así.'] },
  },
  {
    id:'el_tecnico', name:'El Técnico', title:'Experto Electrónica', avatar:'🧑‍🔧',
    desc:'Ingeniero retirado, restaura equipos electrónicos vintage.',
    pref:['electronics','machines'],
    mult:{ videogames:1.0, electronics:1.3, machines:1.2, rarities:0.9, art:0.75, music:0.9 },
    tradeFreq:4,
    phrases:{ buy:['Veo potencial en esto.','Lo puedo restaurar, vale más de lo que crees.','Trato hecho si me lo dejas a buen precio.'] },
  },
  {
    id:'ramiro', name:'Ramiro', title:'Revendedor', avatar:'🤵',
    desc:'Comprador y vendedor con ojo para el negocio.',
    pref:[],
    mult:{ videogames:0.88, electronics:0.88, machines:0.88, rarities:0.88, art:0.88, music:0.88 },
    tradeFreq:5,
    phrases:{ buy:['Lo tomo, pero no puedo pagar más.','El mercado está difícil, pero lo llevo.','¿Lo tomas o lo dejo?'] },
  },
  {
    id:'dra_vega', name:'Dra. Vega', title:'Historiadora', avatar:'👩‍🎓',
    desc:'Profesora universitaria, especialista en historia tecnológica.',
    pref:['rarities','electronics','music'],
    mult:{ videogames:0.85, electronics:1.15, machines:1.1, rarities:1.2, art:1.05, music:1.15 },
    tradeFreq:2,
    gradeBonus:true,
    phrases:{ buy:['Fascinante. Esto tiene valor histórico real.','Para mi investigación es perfecto.','Artículo excepcional para mi colección.'] },
  },
  {
    id:'misterioso', name:'El Misterioso', title:'???', avatar:'🎭',
    desc:'Nadie sabe su nombre real. Aparece raramente con ofertas extraordinarias.',
    pref:['unique','legendary'],
    mult:{ videogames:2.0, electronics:2.0, machines:2.0, rarities:2.0, art:2.0, music:2.0 },
    tradeFreq:1,
    phrases:{ buy:['...','Sé lo que vale realmente.','Nadie más te pagará esto.'] },
  },
];

const BODEGAS = [
  {
    id:'basica', name:'Bodega Básica', icon:'🏚️', cost:300,
    desc:'Un almacén sencillo con mercancía variada y polvorosa.',
    itemCount:{ min:2, max:4 },
    rarityW:{ common:72, rare:25, epic:3, legendary:0, unique:0 },
    conditionW:{ new:10, used:35, damaged:35, very_damaged:20 },
    unidChance:0.15, color:'#607d8b',
  },
  {
    id:'estandar', name:'Bodega Estándar', icon:'🏭', cost:800,
    desc:'Contenido variado con mejores probabilidades de hallazgos.',
    itemCount:{ min:3, max:5 },
    rarityW:{ common:58, rare:34, epic:7, legendary:1, unique:0 },
    conditionW:{ new:15, used:40, damaged:30, very_damaged:15 },
    unidChance:0.20, color:'#1976d2',
  },
  {
    id:'premium', name:'Bodega Premium', icon:'🏬', cost:2000,
    desc:'Colección seleccionada de alta calidad y excelente conservación.',
    itemCount:{ min:4, max:6 },
    rarityW:{ common:40, rare:38, epic:18, legendary:3, unique:1 },
    conditionW:{ new:25, used:45, damaged:20, very_damaged:10 },
    unidChance:0.30, color:'#7b1fa2',
  },
  {
    id:'rara', name:'Bodega Rara', icon:'🏴‍☠️', cost:5000,
    desc:'Artículos inusuales de procedencia misteriosa.',
    itemCount:{ min:3, max:5 },
    rarityW:{ common:18, rare:42, epic:30, legendary:8, unique:2 },
    conditionW:{ new:20, used:30, damaged:30, very_damaged:20 },
    unidChance:0.50, color:'#e64a19',
  },
  {
    id:'misteriosa', name:'Bodega Misteriosa', icon:'🔮', cost:12000,
    desc:'Nadie sabe qué hay dentro... sólo lo más extraordinario.',
    itemCount:{ min:4, max:7 },
    rarityW:{ common:10, rare:30, epic:38, legendary:17, unique:5 },
    conditionW:{ new:30, used:30, damaged:25, very_damaged:15 },
    unidChance:0.60, color:'#ad1457',
  },
  {
    id:'magnate', name:'Bóveda del Magnate', icon:'🏛️', cost:150000,
    desc:'Lo mejor del catálogo, sin desperdicios. Cero comunes, cero raros. Solo lo que vale.',
    itemCount:{ min:5, max:8 },
    rarityW:{ epic:45, legendary:40, unique:15 },
    conditionW:{ new:60, used:35, damaged:5, very_damaged:0 },
    unidChance:0, color:'#FFD700', minLevel:10,
  },
  {
    id:'abismo', name:'Caja del Abismo', icon:'💀', cost:250000,
    desc:'Items exclusivos que no existen en ninguna otra bodega. 2% de probabilidad de obtener algo exótico.',
    itemCount:{ min:2, max:4 },
    rarityW:{ epic:45, legendary:35, unique:18, exotic:2 },
    conditionW:{ new:80, used:20, damaged:0, very_damaged:0 },
    unidChance:0, color:'#39FF14', minLevel:20,
    abismoOnly:true,
  },
];

const ACHIEVEMENTS = [
  { id:'first_bodega',   icon:'🔑', name:'Primera Bodega',      desc:'Abre tu primera bodega.',             check: s => s.stats.bodegas >= 1 },
  { id:'bodega_10',      icon:'🏭', name:'Bodeguero',           desc:'Abre 10 bodegas.',                    check: s => s.stats.bodegas >= 10 },
  { id:'first_rare',     icon:'💙', name:'Primer Raro',         desc:'Obtén tu primer objeto raro.',        check: s => s.stats.found_rare >= 1 },
  { id:'first_epic',     icon:'💜', name:'Primer Épico',        desc:'Obtén tu primer objeto épico.',       check: s => s.stats.found_epic >= 1 },
  { id:'first_legendary',icon:'🏆', name:'Primer Legendario',   desc:'Obtén tu primer objeto legendario.', check: s => s.stats.found_legendary >= 1 },
  { id:'first_unique',   icon:'💫', name:'Objeto Único',        desc:'Obtén un objeto único.',              check: s => s.stats.found_unique >= 1 },
  { id:'rich',           icon:'💰', name:'Rico',                desc:'Alcanza 10,000 monedas.',             check: s => s.money >= 10000 },
  { id:'millionaire',    icon:'🤑', name:'Millonario',          desc:'Alcanza 100,000 monedas.',            check: s => s.money >= 100000 },
  { id:'sold_10',        icon:'💼', name:'Comerciante',         desc:'Completa 10 ventas.',                 check: s => s.stats.sold >= 10 },
  { id:'repaired_5',     icon:'🔧', name:'Manitas',             desc:'Repara 5 objetos.',                   check: s => s.stats.repaired >= 5 },
  { id:'bj_10',          icon:'🃏', name:'Tahúr',               desc:'Gana 10 manos de blackjack.',         check: s => s.stats.bj_wins >= 10 },
  { id:'bj_streak5',     icon:'🔥', name:'Racha de Fuego',      desc:'Consigue una racha de 5 victorias.',  check: s => s.stats.bj_best_streak >= 5 },
  { id:'level_5',        icon:'⭐', name:'Aprendiz',            desc:'Alcanza el nivel 5.',                 check: s => s.level >= 5 },
  { id:'level_10',       icon:'🌟', name:'Veterano',            desc:'Alcanza el nivel 10.',                check: s => s.level >= 10 },
  { id:'level_25',       icon:'✨', name:'Maestro',             desc:'Alcanza el nivel 25.',                check: s => s.level >= 25 },
  { id:'collector_20',   icon:'📚', name:'Coleccionista',       desc:'Descubre 20 objetos distintos.',      check: s => Object.keys(s.collection).length >= 20 },
  { id:'collector_all',  icon:'🎖️', name:'Completista',         desc:'Descubre todos los objetos.',         check: s => Object.keys(s.collection).length >= CATALOG.length },
];

// ── RULETA ────────────────────────────────────────────────
const ROULETTE_PRIZES = [
  { type:'nothing', label:'Sin suerte hoy…',  weight:40, color:'#607d8b' },
  { type:'xp',      label:'+150 XP',          weight:25, value:150, color:'#6c63ff' },
  { type:'xp',      label:'+300 XP',          weight:10, value:300, color:'#4a44cc' },
  { type:'coins',   label:'+200 monedas',      weight:15, value:200, color:'#f0c040' },
  { type:'coins',   label:'+500 monedas',      weight:7,  value:500, color:'#ffaa00' },
  { type:'bodega',  label:'¡Bodega gratis!',   weight:3,  value:'basica', color:'#e91e63' },
];

// ── RECOMPENSAS POR NIVEL ─────────────────────────────────
const LEVEL_REWARDS_MAP = {
  2:  [{ type:'coins', amount:150 }],
  3:  [{ type:'bodega', id:'basica', label:'Bodega Básica' }],
  4:  [{ type:'coins', amount:300 }],
  5:  [{ type:'bodega', id:'estandar', label:'Bodega Estándar' }, { type:'showcase_slots', count:1 }],
  6:  [{ type:'coins', amount:500 }, { type:'item', catalogId:'exclusive_compass', label:'Brújula Náutica' }],
  7:  [{ type:'bodega', id:'estandar', label:'Bodega Estándar' }, { type:'coins', amount:300 }],
  8:  [{ type:'coins', amount:800 }],
  9:  [{ type:'item', catalogId:'exclusive_lamp', label:'Lámpara de Araña' }, { type:'bodega', id:'premium', label:'Bodega Premium' }],
  10: [{ type:'coins', amount:1500 }, { type:'bodega', id:'premium', label:'Bodega Premium' }, { type:'bodega', id:'premium', label:'Bodega Premium' }, { type:'showcase_slots', count:2 }],
  12: [{ type:'coins', amount:1000 }, { type:'bodega', id:'premium', label:'Bodega Premium' }],
  15: [{ type:'item', catalogId:'exclusive_armor', label:'Armadura Medieval' }, { type:'bodega', id:'rara', label:'Bodega Rara' }, { type:'bodega', id:'rara', label:'Bodega Rara' }, { type:'coins', amount:2000 }, { type:'showcase_slots', count:2 }],
  20: [{ type:'item', catalogId:'exclusive_crown', label:'Corona Imperial' }, { type:'bodega', id:'misteriosa', label:'Bodega Misteriosa' }, { type:'coins', amount:5000 }, { type:'showcase_slots', count:2 }],
};

// Slots de vitrina desbloqueados por nivel
function showcaseSlotsForLevel(level) {
  if (level >= 20) return 7;
  if (level >= 15) return 5;
  if (level >= 10) return 3;
  if (level >= 5)  return 1;
  return 0;
}

// ── REVESTIMIENTOS DE VITRINA ─────────────────────────────
const REVESTIMIENTOS = [
  // Común
  { id:'madera_rustica',     name:'Madera Rústica',     rarity:'common',    desc:'Marco de madera sin tratar con vetas naturales.',         cssClass:'rev-madera-rustica' },
  { id:'piedra_gris',        name:'Piedra Gris',         rarity:'common',    desc:'Marco de piedra pulida, sobrio y resistente.',            cssClass:'rev-piedra-gris' },
  { id:'tela_beige',         name:'Tela Beige',          rarity:'common',    desc:'Marco tapizado en tela suave color crema.',               cssClass:'rev-tela-beige' },
  { id:'bambu',              name:'Bambú',               rarity:'common',    desc:'Marco de bambú natural, ligero y elegante.',              cssClass:'rev-bambu' },
  { id:'cuero_marron',       name:'Cuero Marrón',        rarity:'common',    desc:'Marco de cuero genuino cosido a mano.',                   cssClass:'rev-cuero-marron' },
  // Raro
  { id:'marmol',             name:'Mármol',              rarity:'rare',      desc:'Marco de mármol blanco con vetas grises y brillo suave.', cssClass:'rev-marmol' },
  { id:'metal_plateado',     name:'Metal Plateado',      rarity:'rare',      desc:'Marco de aluminio pulido con reflejos plateados.',        cssClass:'rev-metal-plateado' },
  { id:'cuero_negro',        name:'Cuero Negro',         rarity:'rare',      desc:'Marco de cuero negro con costuras visibles.',             cssClass:'rev-cuero-negro' },
  { id:'terciopelo_azul',    name:'Terciopelo Azul',     rarity:'rare',      desc:'Marco tapizado en terciopelo azul real.',                 cssClass:'rev-terciopelo-azul' },
  { id:'madera_lacada',      name:'Madera Lacada',       rarity:'rare',      desc:'Marco de madera con acabado brillante lacado.',           cssClass:'rev-madera-lacada' },
  { id:'cobre',              name:'Cobre Pulido',        rarity:'rare',      desc:'Marco de cobre con brillo cálido y rojizo.',              cssClass:'rev-cobre' },
  { id:'jade',               name:'Jade Verde',          rarity:'rare',      desc:'Marco de jade con suave brillo verdoso.',                 cssClass:'rev-jade' },
  // Épico
  { id:'cristal_azul',       name:'Cristal Azul',        rarity:'epic',      desc:'Marco de cristal azul con pulso luminoso.',              cssClass:'rev-cristal-azul' },
  { id:'obsidiana',          name:'Obsidiana',           rarity:'epic',      desc:'Marco de obsidiana oscura con reflejos púrpura.',        cssClass:'rev-obsidiana' },
  { id:'terciopelo_purpura', name:'Terciopelo Púrpura',  rarity:'epic',      desc:'Marco de terciopelo púrpura con aura pulsante.',         cssClass:'rev-terciopelo-purpura' },
  { id:'titanio',            name:'Titanio',             rarity:'epic',      desc:'Marco de titanio con brillo metálico azulado.',          cssClass:'rev-titanio' },
  { id:'ambar',              name:'Ámbar',               rarity:'epic',      desc:'Marco de ámbar con resplandor cálido dorado.',           cssClass:'rev-ambar' },
  { id:'bronce_antiguo',     name:'Bronce Antiguo',      rarity:'epic',      desc:'Marco de bronce envejecido con pátina verde.',           cssClass:'rev-bronce-antiguo' },
  { id:'esmeralda',          name:'Esmeralda',           rarity:'epic',      desc:'Marco de esmeralda con pulso luminoso verde.',           cssClass:'rev-esmeralda' },
  // Legendario
  { id:'llamas_rojas',       name:'Llamas Rojas',        rarity:'legendary', desc:'Marco envuelto en llamas rojas que nunca se apagan.',    cssClass:'rev-llamas-rojas' },
  { id:'plasma_dorado',      name:'Plasma Dorado',       rarity:'legendary', desc:'Marco de plasma dorado en constante movimiento.',        cssClass:'rev-plasma-dorado' },
  { id:'hielo_artico',       name:'Hielo Ártico',        rarity:'legendary', desc:'Marco de hielo ártico con cristales de escarcha.',       cssClass:'rev-hielo-artico' },
  { id:'tormenta_electrica', name:'Tormenta Eléctrica',  rarity:'legendary', desc:'Marco con destellos eléctricos recorriendo el borde.',  cssClass:'rev-tormenta-electrica' },
  // Único
  { id:'arcoiris',           name:'Arcoíris',            rarity:'unique',    desc:'Marco con todos los colores del espectro en movimiento.',cssClass:'rev-arcoiris' },
  { id:'galaxia',            name:'Galaxia',             rarity:'unique',    desc:'Marco con nebulosas y estrellas en rotación cósmica.',   cssClass:'rev-galaxia' },
];

const CAJA_DISENADOR = {
  id:'caja_disenador', name:'Caja de Diseñador', icon:'🎨', cost:45000,
  desc:'Contiene un revestimiento visual exclusivo para tu vitrina. Mismas probabilidades que la Bodega Misteriosa.',
  rarityW:{ common:10, rare:30, epic:38, legendary:17, unique:5 },
  minLevel: 5,
  color:'#ff6b35',
};

function xpForLevel(level) {
  return Math.floor(100 * Math.pow(1.30, level - 1));
}

function levelRewards(level) {
  const r = [{ type:'money', amount: level * 75 + 100 }];
  if (level % 5  === 0) r.push({ type:'bodega', id:'estandar' });
  if (level % 10 === 0) r.push({ type:'bodega', id:'premium' });
  if (level % 20 === 0) r.push({ type:'bodega', id:'rara' });
  return r;
}
